on:
  push:
    branches: [main]

name: Quarto Publish

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Python packages
        run: |
          pip install polars plotnine pandas jupyter pyyaml nbformat ipykernel geopandas fiona

      - uses: quarto-dev/quarto-actions/setup@v2

      - name: Render Quarto
        run: quarto render unicef_report.qmd

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .
          publish_branch: gh-pages
